# Generated by Django 6.1 on 2026-09-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(default='Ronan Auto Center', max_length=255)),
                ('endereco_completo', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='acesso_clientes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='acesso_configuracoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='acesso_estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='acesso_orcamentos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='acesso_servicos',
            field=models.BooleanField(default=True),
        ),
    ]
