# Generated by Django 6.1 on 2026-09-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_configuracao_perfil_acesso_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peca',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servico',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
